
document.getElementById("js-signup-button").addEventListener("click", function (event) {
  event.preventDefault();

  // Create a JSON object from the form data
  const formData = {
    customerid: "", // You can leave this empty as it seems to be generated by your server.
    name: document.getElementById("name").value,
    emailid: document.getElementById("email").value,
    password: document.getElementById("password").value,
    confirmpassword: document.getElementById("confirm_password").value,
  };
  console.log("Request sent");
  fetch("/registercustomer", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(formData),
  })
    .then(response => response.json())
    .then(data => {
      if (data && data.value) {
        alert(data.value.message);
      } else {
        alert("Failed: " + data.error);
      }
      window.location.href = '/signin';
    })
    .catch(error => {
      console.error("Error:", error);
      alert("Error while creating customer profile: " + error.message);
    });
});

